name: oasis-ctcf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=24
  - setuptools
  - wheel
  - numpy
  - scipy
  - scikit-image
  - matplotlib
  - imageio
  - tifffile
  - ml-collections
  - pip:
      - torch
      - torchvision
      - torchaudio
      - natsort
      - tensorboard
      - tqdm
      - einops
      - timm
      - pystrum
      - safetensors
      - huggingface-hub
      - markdown
      - surface-distance
      - werkzeug
